services:
  app:
    image: ${ACR_LOGIN_SERVER}/${APP_IMAGE_NAME:-appgym-app}:${IMAGE_TAG:-latest}
    ports:
      - "8080:80"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-appgym}
      - MONGODB_USERS_COLLECTION=${MONGODB_USERS_COLLECTION:-usuarios}
